### ISSUE TITLE
'Country' picker

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#18]
Letting the user type the 'Country' attribution by themself rather than picking it from a predefined list (associated with country codes) will cause problems for statistics or the display of country-flags.

**Comment by olastor** [comment]
[Possible list](https://gist.github.com/Keeguon/2310008) for countries

**Comment by binarious** [comment]
Right, that's the reason for the Flags part in the README todo, but good to have a separate issue for that. It's currently blocked, because I wanted to wait for the `md-select` implementation of angular2/material: https://github.com/angular/material2/issues/118
Maybe we should just use the native select for now.

**Comment by binarious** [comment]
Fixed with native select in https://github.com/Sirimangalo/meditation-plus-angular/commit/51f79efc58a4ccad7ac85e24fc9de1e4831a551d
