### ISSUE TITLE
Adding Meditation, Chat and Commit to main menu button

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#196]
A minor useability improvement: If you're on say the scheduling page and want to go check out "Chat" you first have to go to "Home" on the main menu and then switch to the chat tab.  I think it makes more sense to have the three tabs on the home screen directly accessible from the main menu.  Then you wouldn't need the "Home" menu option.

**Comment by binarious** [comment]
I think this redundancy is more confusing than helping, because it suggests that there is another meditation, chat and commit view than the one on home. It's also unusual since a lot of popular apps aren't doing this, too. Additionally it would increase the menu size which is already on its limit on smartphones and then they would have to scroll.
