### ISSUE TITLE
Chat sort order a little screwy

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#234]
You can't see this bug unless there is a recent flurry of activity on chat.  Posts in the past hour (i.e. that were "minutes ago") are appearing out of order such that something posted 2 minutes ago appears before something posted 6 minutes ago.

Maybe its being sorted by ID rather than time posted.  An auto ID assigned when the user begins editing the record but the timestamp is assigned when the record is posted?  Something like that.

**Comment by binarious** [comment]
>Maybe its being sorted by ID rather than time posted.

No they're [sorted by date](https://github.com/Sirimangalo/meditation-plus-server/blob/fa0ebaf67cada6a75b3e1361dd452ec0ed329c25/src/app/routes/_message.router.js#L23) of creation.
Messages are received in realtime via WebSocket broadcasts, but when you have network disturbances or your browser stops the WebSocket connection, because of battery savings or similar, then messages are missed. We have an interval to fetch these missed messages, but they could end up in the wrong place when newer ones have already been fetched before this interval fires.

I will check if there's a better solution.
