### ISSUE TITLE
Answered questions should be sorted in the order they were answered

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#252]
@Yuttadhammo requested this in the daily broadcast.  Apparently the questions on the answered tab are not in a useful order so if someone accidentally marks a question as answered when it hasn't been it is hard to find.

**Comment by bkeevil** [comment]
And I was curious how long those questions stay on the answered tab?

**Comment by binarious** [comment]
When https://github.com/Sirimangalo/meditation-plus-angular/issues/198 gets integrated it makes more sense to have them ordered by thumbs up in my opinion. The questions currently stay there forever. @yuttadhammo what shall we do with the answered tab considering #198 lands soon.

**Comment by yuttadhammo** [comment]
For questions not yet answered, they should be ordered by votes, but once
they are marked as answered, by age would be useful... i don't understand
the connection with the live stream...

**Comment by binarious** [comment]
The questions will get a link to the YouTube video at the position slightly before they've been marked as answered. So it makes more sense to have the most liked answered question at the top. Why would you prefer them to be ordered by date?

**Comment by yuttadhammo** [comment]
Ah i see... Actually it was just because i mistakenly marked one as
answered, then had a difficult time finding it in the answered section

On Sep 3, 2016 4:32 AM, "binarious" <notifications@github.com> wrote:

The questions will get a link to the YouTube video at the position slightly
before they've been marked as answered. So it makes more sense to have the
most liked answered question at the top. Why would you prefer them to be
ordered by date?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sirimangalo/meditation-plus-angular/issues/252#issuecomment-244534537>,
or mute the thread

**Comment by yuttadhammo** [comment]
I still think order by age is better... It will still be generally by rank,
since we answer higher ranked questions first

**Comment by binarious** [comment]
So you mean order it by the time it has been answered? Currently it's ordered by the time of creation.

**Comment by yuttadhammo** [comment]
Ah, right, i guess it would have to be so... I guess ordering by time
answered would be convenient for looking over... Not imperative i think.

**Comment by bkeevil** [comment]
Maybe this should be a separate ticket but there is a privacy issue too then.  Some users may be reluctant to ask questions if they think their names will be published online indefinitely.  Is it necessary to list the person's name at all?

**Comment by binarious** [comment]
Thought about that, too. We could add the option to ask anonymously.
