### ISSUE TITLE
no avatar in meditation+ site after gravatar upload (bug)

### ISSUE THREAD

**Issue by meditator3** [Sirimangalo/meditation-plus-angular#308]
hi,
somehow i get my avatar here from gravatar, but on meditation+ website it doesn't update?

**Comment by binarious** [comment]
Have you tried clearing the browser cache? Can you please send me the link to your profile?

**Comment by meditator3** [comment]
just cleared my cache, no effecthere is my link to my profileMeditation+ | Sirimangalo
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Meditation+ | Sirimangalo
 Meditation+ | Sirimangalo  |   |

  |

  |

 
 

    On Monday, September 26, 2016 8:26 PM, binarious <notifications@github.com> wrote:
 

 Have you tried clearing the browser cache? Can you please send me the link to your profile?—

**Comment by meditator3** [comment]
here is the link 
https://meditation.sirimangalo.org/profile/57cdc2f037dfb9df060e2305

**Comment by olastor** [comment]
Your gravatar link also shows no image
 https://www.gravatar.com/avatar/15208a28d6105fb02eeee57dc350b4ad 

You can check if the link is correct by generating a md5 hash (http://www.miraclesalad.com/webtools/md5.php) of your email address. If you've entered your email there and the md5 hash is

15208a28d6105fb02eeee57dc350b4ad

this means the link is correct. Have you maybe used a different email for gravatar? Otherwise try to setup gravatar once again.

**Comment by meditator3** [comment]
no its the same email. i think its something to do with the rating?
I've marked it PG. is that ok? what rating is recommended?

**Comment by binarious** [comment]
I checked your mail with https://gravatar.com/site/check/ and it's missing the `G` rating.
From the Gravatar website: 
> By default, only 'G' rated images are displayed

So please rate it as G.

**Comment by meditator3** [comment]
thanks!! that was the problem :)
