### ISSUE TITLE
Bell not working in android

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#402]
The bell between the walking and sitting works but not the one to end the sitting meditation.  Hasnt worked for a while.

**Comment by olastor** [comment]
Have you activated the "stable bell" feature in the profile settings?

**Comment by bkeevil** [comment]
No.  I  don't want to download a large sound file every time I meditate when I can just play one locally.

**Comment by binarious** [comment]
It downloads just once and is cached until we release a new version. If not, then it's a bug or your (smartphone's) browser doesn't support modern caching mechanisms. The normal bell has always been buggy unfortunately due to browser limitations. Closing as dupe of https://github.com/Sirimangalo/meditation-plus-angular/issues/300. We'll fix the "normal" bell as soon as new possibilities occur.
